<?php
/**
 * Leo bootstrap menu Module
 * 
 * @version		$Id: file.php $Revision
 * @package		modules
 * @subpackage	$Subpackage.
 * @copyright	Copyright (C) September 2012 LeoTheme.Com <@emai:leotheme@gmail.com>.All rights reserved.
 * @license		GNU General Public License version 2
 */
 
/* REQUIRED */
if (!defined('_PS_VERSION_'))
	exit;
$path = dirname( _PS_ADMIN_DIR_ );
 
include_once( $path. '/config/config.inc.php');
include_once( $path.'/init.php');

$res = (bool)Db::getInstance()->execute('
	CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'btmegamenu` (
	  `id_btmegamenu` int(11) NOT NULL AUTO_INCREMENT,
	  `image` varchar(255) NOT NULL,
	  `id_parent` int(11) NOT NULL,
	  `is_group` tinyint(1) NOT NULL,
	  `width` varchar(255) DEFAULT NULL,
	  `submenu_width` varchar(255) DEFAULT NULL,
	  `colum_width` varchar(255) DEFAULT NULL,
	  `submenu_colum_width` varchar(255) DEFAULT NULL,
	  `item` varchar(255) DEFAULT NULL,
	  `colums` varchar(255) DEFAULT NULL,
	  `type` varchar(255) NOT NULL,
	  `is_content` tinyint(1) NOT NULL,
	  `show_title` tinyint(1) NOT NULL,
	  `type_submenu` varchar(10) NOT NULL,
	  `level_depth` smallint(6) NOT NULL,
	  `active` tinyint(1) NOT NULL,
	  `position` int(11) NOT NULL,
	  `show_sub` tinyint(1) NOT NULL,
	  `url` varchar(255) DEFAULT NULL,
	  `target` varchar(25) DEFAULT NULL,
	  `privacy` smallint(6) DEFAULT NULL,
	  `position_type` varchar(25) DEFAULT NULL,
	  `menu_class` varchar(25) DEFAULT NULL,
	  `content` text,
	  `submenu_content` text,
	  `level` int(11) NOT NULL,
	  `left` int(11) NOT NULL,
	  `right` int(11) NOT NULL,
      `submenu_catids` text,
      `is_cattree` tinyint(1) DEFAULT 1,
	  `date_add` datetime DEFAULT NULL,
	  `date_upd` datetime DEFAULT NULL,
	  PRIMARY KEY (`id_btmegamenu`)
	) ENGINE='._MYSQL_ENGINE_.'  DEFAULT CHARSET=utf8;
');
$res &= (bool)Db::getInstance()->execute('
	CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'btmegamenu_lang` (
	  `id_btmegamenu` int(11) NOT NULL,
	  `id_lang` int(11) NOT NULL,
	  `title` varchar(255) DEFAULT NULL,
	  `description` text,
	  `content_text` text,
	  `submenu_content_text` text,
	  PRIMARY KEY (`id_btmegamenu`,`id_lang`)
	) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;
');
$res &= (bool)Db::getInstance()->execute('
	CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'btmegamenu_shop` (
	  `id_btmegamenu` int(11) NOT NULL DEFAULT \'0\',
	  `id_shop` int(11) NOT NULL DEFAULT \'0\',
	  PRIMARY KEY (`id_btmegamenu`,`id_shop`)
	) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;
');
$res &= (bool)Db::getInstance()->execute("
INSERT INTO `"._DB_PREFIX_."btmegamenu` (`id_btmegamenu`, `image`, `id_parent`, `is_group`, `width`, `submenu_width`, `colum_width`, `submenu_colum_width`, `item`, `colums`, `type`, `is_content`, `show_title`, `type_submenu`, `level_depth`, `active`, `position`, `show_sub`, `url`, `target`, `privacy`, `position_type`, `menu_class`, `content`, `submenu_content`, `level`, `left`, `right`, `submenu_catids`, `is_cattree`, `date_add`, `date_upd`) VALUES
(1, '', 0, 1, NULL, NULL, NULL, NULL, NULL, '1', '', 0, 0, '', 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, NULL, 1, NULL, NULL),
(2, '', 1, 0, '', '', '', '', '', '1', 'url', 0, 1, 'menu', 1, 1, 0, 0, 'index.php', '_self', 0, '', '', '', '', 0, 0, 0, '', 1, '2013-03-11 02:04:56', '2013-09-08 03:49:55'),
(3, '', 1, 0, '', '', '', '', '2', '1', 'category', 0, 1, 'menu', 1, 1, 3, 0, '', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-11 02:07:30', '2013-05-13 22:11:17'),
(17, '', 1, 0, '', '', '', 'col3=4 col3=4 col3=4', '3', '3', 'category', 0, 1, 'category', 1, 1, 1, 0, '#', '_self', 0, '', '', '', '', 0, 0, 0, '7,8,6,12,14,15,3,4,16,17,18,5', 1, '2013-03-11 06:27:16', '2013-08-26 00:55:51'),
(32, '', 45, 0, '', '', '', '', '3', '1', 'category', 1, 1, 'menu', 4, 1, 0, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 03:57:01', '2013-06-10 00:03:34'),
(41, '', 1, 0, '', '', '', '', '2', '1', 'cms', 0, 0, 'menu', 1, 1, 2, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 04:34:13', '2013-06-09 22:31:31'),
(42, '', 41, 1, '', '', '', '', '', '3', 'url', 0, 0, 'menu', 2, 1, 0, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 04:35:02', '2013-03-12 05:22:58'),
(43, '', 41, 0, '', '', '', '', '', '1', 'html', 0, 1, 'menu', 2, 1, 1, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 04:35:24', '2013-03-13 04:45:28'),
(44, '', 47, 0, '', '', '', '', '', '1', 'url', 0, 1, 'menu', 4, 1, 1, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 04:35:49', '2013-03-20 05:46:46'),
(45, '', 42, 1, '', '', '', '', '', '1', 'url', 0, 1, 'menu', 3, 1, 0, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 04:42:48', '2013-04-08 00:35:08'),
(46, '', 42, 1, '', '', '', '', '', '1', 'url', 0, 1, 'menu', 3, 1, 2, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 04:44:28', '2013-03-12 05:34:10'),
(47, '', 42, 1, '', '', '', '', '', '1', 'url', 0, 1, 'menu', 3, 1, 1, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 04:45:32', '2013-04-03 05:33:03'),
(49, '', 47, 0, '', '', '', '', '', '1', 'url', 0, 1, 'menu', 4, 1, 0, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 05:32:55', '2013-03-12 05:32:55'),
(51, '', 46, 0, '', '', '', '', '', '1', 'url', 0, 1, 'menu', 4, 1, 0, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 05:57:48', '2013-03-12 05:57:48'),
(52, '', 1, 0, '', '', '', '', '1', '1', 'cms', 0, 1, 'menu', 1, 1, 4, 0, '', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 06:13:30', '2013-03-12 06:13:30'),
(53, '', 1, 0, '', '', '', '', '4', '1', 'cms', 0, 1, 'menu', 1, 1, 5, 0, '', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-12 06:14:02', '2013-03-12 06:14:02'),
(54, '', 46, 0, '', '', '', '', '', '1', 'url', 0, 1, 'menu', 4, 1, 1, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-13 03:58:03', '2013-03-13 03:58:03'),
(55, '', 45, 0, '', '', '', '', '', '1', 'url', 0, 1, 'menu', 4, 1, 1, 0, '#', '', 0, '', '', '', '', 0, 0, 0, NULL, 1, '2013-03-13 03:59:09', '2013-03-13 03:59:09');
");

$res &= (bool)Db::getInstance()->execute("INSERT INTO `"._DB_PREFIX_."btmegamenu_lang` (`id_btmegamenu`, `id_lang`, `title`, `description`, `content_text`, `submenu_content_text`) VALUES
(1, 1, 'Root', NULL, NULL, NULL),
(1, 2, 'Root', NULL, NULL, NULL),
(1, 3, 'Root', NULL, NULL, NULL),
(1, 4, 'Root', NULL, NULL, NULL),
(1, 5, 'Root', NULL, NULL, NULL),
(1, 6, 'Root', NULL, NULL, NULL),
(1, 7, 'Root', NULL, NULL, NULL),
(1, 8, 'Root', NULL, NULL, NULL),
(1, 9, 'Root', NULL, NULL, NULL),
(2, 1, 'Home', '', '', ''),
(2, 2, 'Zuhause', '', '', ''),
(2, 3, 'Magasiner', '', '', ''),
(2, 4, 'Casa', '', '', ''),
(2, 5, 'Domestico', '', '', ''),
(2, 6, 'Casa', '', '', ''),
(2, 7, 'Home', '', '', ''),
(2, 8, 'Dom', '', '', ''),
(2, 9, 'Home', '', '', ''),
(3, 1, 'Shop', '', '', ''),
(3, 2, 'Shop', '', '', ''),
(3, 3, 'Shop', '', '', ''),
(3, 4, 'Loja', '', '', ''),
(3, 5, 'Negozio', '', '', ''),
(3, 6, 'Tienda', '', '', ''),
(3, 7, 'магазин', '', '', ''),
(3, 8, 'Shop', '', '', ''),
(3, 9, 'Shop', '', '', ''),
(17, 1, 'Categories', '', '', ''),
(17, 2, 'Kategorien', '', '', ''),
(17, 3, 'Catégories', '', '', ''),
(17, 4, 'Catégories', '', '', ''),
(17, 5, 'Categorías', '', '', ''),
(17, 6, 'Categories', '', '', ''),
(17, 7, 'Категории', '', '', ''),
(17, 8, 'Kategorie', '', '', ''),
(17, 9, 'Categories', '', '', ''),
(32, 1, 'Proin ac sapien ut', '', '', ''),
(32, 2, 'Proin ac sapien ut', '', '', ''),
(32, 3, 'Proin ac sapien ut', '', '', ''),
(32, 4, 'Proin ac sapien ut', '', '', ''),
(32, 5, 'Proin ac sapien ut', '', '', ''),
(32, 6, 'Proin ac sapien ut', '', '', ''),
(32, 7, 'Proin ac sapien ut', '', '', ''),
(32, 8, 'Proin ac sapien ut', '', '', ''),
(32, 9, 'Proin ac sapien ut', '', '', ''),
(41, 1, 'Community', '', '', ''),
(41, 2, 'Gemeinschaft', '', '', ''),
(41, 3, 'Communauté', '', '', ''),
(41, 4, 'Comunidade', '', '', ''),
(41, 5, 'Comunità', '', '', ''),
(41, 6, 'Comunidad', '', '', ''),
(41, 7, 'Community', '', '', ''),
(41, 8, 'Community', '', '', ''),
(41, 9, 'Community', '', '', ''),
(42, 1, 'Aliquam eu velit dolo', '', '', ''),
(42, 2, 'Aliquam eu velit dolo', '', '', ''),
(42, 3, 'Aliquam eu velit dolo', '', '', ''),
(42, 4, 'Aliquam eu velit dolo', '', '', ''),
(42, 5, 'Aliquam eu velit dolo', '', '', ''),
(42, 6, 'Aliquam eu velit dolo', '', '', ''),
(42, 7, 'Aliquam eu velit dolo', '', '', ''),
(42, 8, 'Aliquam eu velit dolo', '', '', ''),
(42, 9, 'Aliquam eu velit dolo', '', '', ''),
(43, 1, 'Aliquam magna liber', '', '<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\" \" /></p>', ''),
(43, 2, 'Aliquam magna liber', '', '<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\" \" /></p>', ''),
(43, 3, 'Aliquam magna liber', '', '<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\" \" /></p>', ''),
(43, 4, 'Aliquam magna liber', '', '<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\" \" /></p>', ''),
(43, 5, 'Aliquam magna liber', '', '<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\" \" /></p>', ''),
(43, 6, 'Aliquam magna liber', '', '<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\" \" /></p>', ''),
(43, 7, 'Aliquam magna liber', '', '<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\" \" /></p>', ''),
(43, 8, 'Aliquam magna liber', '', '<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\" \" /></p>', ''),
(43, 9, 'Aliquam magna liber', '', '<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\" \" /></p>', ''),
(44, 1, 'Custom Module', '', '', ''),
(44, 2, 'Custom Module', '', '', ''),
(44, 3, 'Custom Module', '', '', ''),
(44, 4, 'Custom Module', '', '', ''),
(44, 5, 'Custom Module', '', '', ''),
(44, 6, 'Custom Module', '', '', ''),
(44, 7, 'Custom Module', '', '', ''),
(44, 8, 'Custom Module', '', '', ''),
(44, 9, 'Custom Module', '', '', ''),
(45, 1, 'Custom Module', '', '', ''),
(45, 2, 'Custom Module', '', '', ''),
(45, 3, 'Custom Module', '', '', ''),
(45, 4, 'Custom Module', '', '', ''),
(45, 5, 'Custom Module', '', '', ''),
(45, 6, 'Custom Module', '', '', ''),
(45, 7, 'Custom Module', '', '', ''),
(45, 8, 'Custom Module', '', '', ''),
(45, 9, 'Custom Module', '', '', ''),
(46, 1, 'Aliquam tempus', '', '', ''),
(46, 2, 'Aliquam tempus', '', '', ''),
(46, 3, 'Aliquam tempus', '', '', ''),
(46, 4, 'Aliquam tempus', '', '', ''),
(46, 5, 'Aliquam tempus', '', '', ''),
(46, 6, 'Aliquam tempus', '', '', ''),
(46, 7, 'Aliquam tempus', '', '', ''),
(46, 8, 'Aliquam tempus', '', '', ''),
(46, 9, 'Aliquam tempus', '', '', ''),
(47, 1, 'Donec tempus', '', '', ''),
(47, 2, 'Donec tempus', '', '', ''),
(47, 3, 'Donec tempus', '', '', ''),
(47, 4, 'Donec tempus', '', '', ''),
(47, 5, 'Donec tempus', '', '', ''),
(47, 6, 'Donec tempus', '', '', ''),
(47, 7, 'Donec tempus', '', '', ''),
(47, 8, 'Donec tempus', '', '', ''),
(47, 9, 'Donec tempus', '', '', ''),
(49, 1, 'Vivamus non nisl ut', '', '', ''),
(49, 2, 'Vivamus non nisl ut', '', '', ''),
(49, 3, 'Vivamus non nisl ut', '', '', ''),
(49, 4, 'Vivamus non nisl ut', '', '', ''),
(49, 5, 'Vivamus non nisl ut', '', '', ''),
(49, 6, 'Vivamus non nisl ut', '', '', ''),
(49, 7, 'Vivamus non nisl ut', '', '', ''),
(49, 8, 'Vivamus non nisl ut', '', '', ''),
(49, 9, 'Vivamus non nisl ut', '', '', ''),
(51, 1, 'Aliquam eu velit dolo', '', '', ''),
(51, 2, 'Aliquam eu velit dolo', '', '', ''),
(51, 3, 'Aliquam eu velit dolo', '', '', ''),
(51, 4, 'Aliquam eu velit dolo', '', '', ''),
(51, 5, 'Aliquam eu velit dolo', '', '', ''),
(51, 6, 'Aliquam eu velit dolo', '', '', ''),
(51, 7, 'Aliquam eu velit dolo', '', '', ''),
(51, 8, 'Aliquam eu velit dolo', '', '', ''),
(51, 9, 'Aliquam eu velit dolo', '', '', ''),
(52, 1, 'Delivery', '', '', ''),
(52, 2, 'Lieferung', '', '', ''),
(52, 3, 'Livraison', '', '', ''),
(52, 4, 'Entrega', '', '', ''),
(52, 5, 'Consegna', '', '', ''),
(52, 6, 'Entrega', '', '', ''),
(52, 7, 'доставка', '', '', ''),
(52, 8, 'Społeczność', '', '', ''),
(52, 9, 'Delivery', '', '', ''),
(53, 1, 'About Us', '', '', ''),
(53, 2, 'Über uns', '', '', ''),
(53, 3, 'Qui sommes-nous', '', '', ''),
(53, 4, 'Quem Somos', '', '', ''),
(53, 5, 'Chi siamo', '', '', ''),
(53, 6, 'Entrega', '', '', ''),
(53, 7, 'О нас', '', '', ''),
(53, 8, 'O nas', '', '', ''),
(53, 9, 'About Us', '', '', ''),
(54, 1, 'Lorem psum dolor sit ', '', '', ''),
(54, 2, 'Lorem psum dolor sit ', '', '', ''),
(54, 3, 'Lorem psum dolor sit ', '', '', ''),
(54, 4, 'Lorem psum dolor sit ', '', '', ''),
(54, 5, 'Lorem psum dolor sit ', '', '', ''),
(54, 6, 'Lorem psum dolor sit ', '', '', ''),
(54, 7, 'Lorem psum dolor sit ', '', '', ''),
(54, 8, 'Lorem psum dolor sit ', '', '', ''),
(54, 9, 'Lorem psum dolor sit ', '', '', ''),
(55, 1, 'Lorem psum dolor sit ', '', '', ''),
(55, 2, 'Lorem psum dolor sit ', '', '', ''),
(55, 3, 'Lorem psum dolor sit ', '', '', ''),
(55, 4, 'Lorem psum dolor sit ', '', '', ''),
(55, 5, 'Lorem psum dolor sit ', '', '', ''),
(55, 6, 'Lorem psum dolor sit ', '', '', ''),
(55, 7, 'Lorem psum dolor sit ', '', '', ''),
(55, 8, 'Lorem psum dolor sit ', '', '', ''),
(55, 9, 'Lorem psum dolor sit ', '', '', '');
");

$res &= (bool)Db::getInstance()->execute("
INSERT INTO `"._DB_PREFIX_."btmegamenu_shop` (`id_btmegamenu`, `id_shop`) VALUES
(1, 1),
(2, 1),
(3, 1),
(17, 1),
(32, 1),
(41, 1),
(42, 1),
(43, 1),
(44, 1),
(45, 1),
(46, 1),
(47, 1),
(49, 1),
(51, 1),
(52, 1),
(53, 1),
(54, 1),
(55, 1);
");
/* END REQUIRED */


